### ISSUE TITLE
[getting-started] Write an example to create a simple S3 bucket 

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#97]
Write an example to create a simple S3 bucket.
**Tasks:**
- [ ] Create new directory name `s3` under https://github.com/tungbq/aws-lab-with-terraform/tree/main/getting-started
- [ ] Create new `main.tf` file under `s3` directory
- [ ] Follow this [document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket) to create new s3 bucket name `sample-s3-tf` (All the terraform code should locate un main.tf file)
- [ ] Test and verify new bucket are created successfully on AWS
- [ ] Create PR for review
- [ ] Done! ❤️‍🔥 

This would help you learn/hands on Terraform with AWS

**Optional:**
- If you're new on Terraform, you can follow this: https://github.com/tungbq/aws-lab-with-terraform#terraform-getting-started---aws to learn the Terraform first
